blank_issues_enabled: false
contact_links:
  - name: 💬 DH electronics Support
    url: https://github.com/dh-electronics
    about: For questions, issues, or contributions, please see our contact information on our GitHub organization profile.
